// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tour.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ Tour Operations ============
type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuideId       string                 `protobuf:"bytes,1,opt,name=guideId,proto3" json:"guideId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // "easy", "medium", "hard"
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTourRequest) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tour          *Tour                  `protobuf:"bytes,3,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{1}
}

func (x *TourResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GuideId       string                 `protobuf:"bytes,2,opt,name=guideId,proto3" json:"guideId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "draft", "published"
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	IsPublished   bool                   `protobuf:"varint,9,opt,name=isPublished,proto3" json:"isPublished,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,10,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{2}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Tour) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Tour) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishedOnly bool                   `protobuf:"varint,1,opt,name=publishedOnly,proto3" json:"publishedOnly,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // Optional: filter by guide
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursRequest) Reset() {
	*x = GetToursRequest{}
	mi := &file_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursRequest) ProtoMessage() {}

func (x *GetToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursRequest.ProtoReflect.Descriptor instead.
func (*GetToursRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{3}
}

func (x *GetToursRequest) GetPublishedOnly() bool {
	if x != nil {
		return x.PublishedOnly
	}
	return false
}

func (x *GetToursRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMyToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuideId       string                 `protobuf:"bytes,1,opt,name=guideId,proto3" json:"guideId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyToursRequest) Reset() {
	*x = GetMyToursRequest{}
	mi := &file_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyToursRequest) ProtoMessage() {}

func (x *GetMyToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyToursRequest.ProtoReflect.Descriptor instead.
func (*GetMyToursRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyToursRequest) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // To check purchase status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{5}
}

func (x *GetTourByIdRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *GetTourByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tours         []*Tour                `protobuf:"bytes,3,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToursResponse) Reset() {
	*x = ToursResponse{}
	mi := &file_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToursResponse) ProtoMessage() {}

func (x *ToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToursResponse.ProtoReflect.Descriptor instead.
func (*ToursResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{6}
}

func (x *ToursResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToursResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToursResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type PublishTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	GuideId       string                 `protobuf:"bytes,2,opt,name=guideId,proto3" json:"guideId,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	mi := &file_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{7}
}

func (x *PublishTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PublishTourRequest) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

func (x *PublishTourRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// ============ KeyPoint Operations ============
type AddKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	GuideId       string                 `protobuf:"bytes,2,opt,name=guideId,proto3" json:"guideId,omitempty"` // For authorization
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Order         int32                  `protobuf:"varint,8,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyPointRequest) Reset() {
	*x = AddKeyPointRequest{}
	mi := &file_tour_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyPointRequest) ProtoMessage() {}

func (x *AddKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyPointRequest.ProtoReflect.Descriptor instead.
func (*AddKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{8}
}

func (x *AddKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *AddKeyPointRequest) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

func (x *AddKeyPointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddKeyPointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AddKeyPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddKeyPointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddKeyPointRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddKeyPointRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type KeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,3,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPointResponse) Reset() {
	*x = KeyPointResponse{}
	mi := &file_tour_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointResponse) ProtoMessage() {}

func (x *KeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointResponse.ProtoReflect.Descriptor instead.
func (*KeyPointResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{9}
}

func (x *KeyPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeyPointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KeyPointResponse) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Order         int32                  `protobuf:"varint,8,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_tour_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{10}
}

func (x *KeyPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *KeyPoint) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type GetKeyPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // To check if user purchased tour
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsRequest) Reset() {
	*x = GetKeyPointsRequest{}
	mi := &file_tour_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsRequest) ProtoMessage() {}

func (x *GetKeyPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsRequest.ProtoReflect.Descriptor instead.
func (*GetKeyPointsRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{11}
}

func (x *GetKeyPointsRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *GetKeyPointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type KeyPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,3,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	IsPurchased   bool                   `protobuf:"varint,4,opt,name=isPurchased,proto3" json:"isPurchased,omitempty"` // Whether user can see all keypoints
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPointsResponse) Reset() {
	*x = KeyPointsResponse{}
	mi := &file_tour_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointsResponse) ProtoMessage() {}

func (x *KeyPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointsResponse.ProtoReflect.Descriptor instead.
func (*KeyPointsResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{12}
}

func (x *KeyPointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeyPointsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KeyPointsResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *KeyPointsResponse) GetIsPurchased() bool {
	if x != nil {
		return x.IsPurchased
	}
	return false
}

type UpdateKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPointId    string                 `protobuf:"bytes,1,opt,name=keyPointId,proto3" json:"keyPointId,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	GuideId       string                 `protobuf:"bytes,3,opt,name=guideId,proto3" json:"guideId,omitempty"` // For authorization
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeyPointRequest) Reset() {
	*x = UpdateKeyPointRequest{}
	mi := &file_tour_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyPointRequest) ProtoMessage() {}

func (x *UpdateKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateKeyPointRequest) GetKeyPointId() string {
	if x != nil {
		return x.KeyPointId
	}
	return ""
}

func (x *UpdateKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *UpdateKeyPointRequest) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

func (x *UpdateKeyPointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateKeyPointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateKeyPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKeyPointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateKeyPointRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeleteKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPointId    string                 `protobuf:"bytes,1,opt,name=keyPointId,proto3" json:"keyPointId,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	GuideId       string                 `protobuf:"bytes,3,opt,name=guideId,proto3" json:"guideId,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointRequest) Reset() {
	*x = DeleteKeyPointRequest{}
	mi := &file_tour_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointRequest) ProtoMessage() {}

func (x *DeleteKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteKeyPointRequest) GetKeyPointId() string {
	if x != nil {
		return x.KeyPointId
	}
	return ""
}

func (x *DeleteKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *DeleteKeyPointRequest) GetGuideId() string {
	if x != nil {
		return x.GuideId
	}
	return ""
}

type DeleteKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointResponse) Reset() {
	*x = DeleteKeyPointResponse{}
	mi := &file_tour_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointResponse) ProtoMessage() {}

func (x *DeleteKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteKeyPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteKeyPointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ============ Position Simulator ============
type UpdatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRequest) Reset() {
	*x = UpdatePositionRequest{}
	mi := &file_tour_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRequest) ProtoMessage() {}

func (x *UpdatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePositionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *UpdatePositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdatePositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_tour_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{17}
}

func (x *GetPositionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_tour_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{18}
}

func (x *PositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PositionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PositionResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_tour_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{19}
}

func (x *Position) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Position) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// ============ Shopping Cart ============
type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_tour_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{20}
}

func (x *AddToCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *AddToCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_tour_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveFromCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_tour_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{22}
}

func (x *GetCartRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cart          *ShoppingCart          `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_tour_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{23}
}

func (x *CartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CartResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type ShoppingCart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingCart) Reset() {
	*x = ShoppingCart{}
	mi := &file_tour_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingCart) ProtoMessage() {}

func (x *ShoppingCart) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingCart.ProtoReflect.Descriptor instead.
func (*ShoppingCart) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{24}
}

func (x *ShoppingCart) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *ShoppingCart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShoppingCart) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tourName,proto3" json:"tourName,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_tour_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{25}
}

func (x *CartItem) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CartItem) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *CartItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_tour_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{26}
}

func (x *CheckoutRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tokens        []*PurchaseToken       `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_tour_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{27}
}

func (x *CheckoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckoutResponse) GetTokens() []*PurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type PurchaseToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PurchasedAt   string                 `protobuf:"bytes,3,opt,name=purchasedAt,proto3" json:"purchasedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseToken) Reset() {
	*x = PurchaseToken{}
	mi := &file_tour_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseToken) ProtoMessage() {}

func (x *PurchaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseToken.ProtoReflect.Descriptor instead.
func (*PurchaseToken) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{28}
}

func (x *PurchaseToken) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PurchaseToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PurchaseToken) GetPurchasedAt() string {
	if x != nil {
		return x.PurchasedAt
	}
	return ""
}

// ============ Tour Execution ============
type StartExecutionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TouristId      string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	TourId         string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	StartLatitude  float64                `protobuf:"fixed64,3,opt,name=startLatitude,proto3" json:"startLatitude,omitempty"`
	StartLongitude float64                `protobuf:"fixed64,4,opt,name=startLongitude,proto3" json:"startLongitude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartExecutionRequest) Reset() {
	*x = StartExecutionRequest{}
	mi := &file_tour_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExecutionRequest) ProtoMessage() {}

func (x *StartExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExecutionRequest.ProtoReflect.Descriptor instead.
func (*StartExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{29}
}

func (x *StartExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *StartExecutionRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *StartExecutionRequest) GetStartLatitude() float64 {
	if x != nil {
		return x.StartLatitude
	}
	return 0
}

func (x *StartExecutionRequest) GetStartLongitude() float64 {
	if x != nil {
		return x.StartLongitude
	}
	return 0
}

type ExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Execution     *TourExecution         `protobuf:"bytes,3,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_tour_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{30}
}

func (x *ExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionResponse) GetExecution() *TourExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type TourExecution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TouristId          string                 `protobuf:"bytes,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	TourId             string                 `protobuf:"bytes,3,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "active", "completed", "abandoned"
	StartedAt          string                 `protobuf:"bytes,5,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,6,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	LastActivity       string                 `protobuf:"bytes,7,opt,name=lastActivity,proto3" json:"lastActivity,omitempty"`
	StartPosition      *Position              `protobuf:"bytes,8,opt,name=startPosition,proto3" json:"startPosition,omitempty"`
	CompletedKeypoints []*CompletedKeyPoint   `protobuf:"bytes,9,rep,name=completedKeypoints,proto3" json:"completedKeypoints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TourExecution) Reset() {
	*x = TourExecution{}
	mi := &file_tour_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecution) ProtoMessage() {}

func (x *TourExecution) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecution.ProtoReflect.Descriptor instead.
func (*TourExecution) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{31}
}

func (x *TourExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourExecution) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TourExecution) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecution) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TourExecution) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *TourExecution) GetLastActivity() string {
	if x != nil {
		return x.LastActivity
	}
	return ""
}

func (x *TourExecution) GetStartPosition() *Position {
	if x != nil {
		return x.StartPosition
	}
	return nil
}

func (x *TourExecution) GetCompletedKeypoints() []*CompletedKeyPoint {
	if x != nil {
		return x.CompletedKeypoints
	}
	return nil
}

type CompletedKeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeypointId    string                 `protobuf:"bytes,1,opt,name=keypointId,proto3" json:"keypointId,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,2,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedKeyPoint) Reset() {
	*x = CompletedKeyPoint{}
	mi := &file_tour_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedKeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedKeyPoint) ProtoMessage() {}

func (x *CompletedKeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedKeyPoint.ProtoReflect.Descriptor instead.
func (*CompletedKeyPoint) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{32}
}

func (x *CompletedKeyPoint) GetKeypointId() string {
	if x != nil {
		return x.KeypointId
	}
	return ""
}

func (x *CompletedKeyPoint) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type CheckProximityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	TouristId        string                 `protobuf:"bytes,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	CurrentLatitude  float64                `protobuf:"fixed64,3,opt,name=currentLatitude,proto3" json:"currentLatitude,omitempty"`
	CurrentLongitude float64                `protobuf:"fixed64,4,opt,name=currentLongitude,proto3" json:"currentLongitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckProximityRequest) Reset() {
	*x = CheckProximityRequest{}
	mi := &file_tour_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProximityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProximityRequest) ProtoMessage() {}

func (x *CheckProximityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProximityRequest.ProtoReflect.Descriptor instead.
func (*CheckProximityRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{33}
}

func (x *CheckProximityRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CheckProximityRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *CheckProximityRequest) GetCurrentLatitude() float64 {
	if x != nil {
		return x.CurrentLatitude
	}
	return 0
}

func (x *CheckProximityRequest) GetCurrentLongitude() float64 {
	if x != nil {
		return x.CurrentLongitude
	}
	return 0
}

type ProximityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NearKeyPoint   bool                   `protobuf:"varint,3,opt,name=nearKeyPoint,proto3" json:"nearKeyPoint,omitempty"`
	NearbyKeyPoint *KeyPoint              `protobuf:"bytes,4,opt,name=nearbyKeyPoint,proto3" json:"nearbyKeyPoint,omitempty"`
	Distance       float64                `protobuf:"fixed64,5,opt,name=distance,proto3" json:"distance,omitempty"` // Distance in meters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProximityResponse) Reset() {
	*x = ProximityResponse{}
	mi := &file_tour_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProximityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProximityResponse) ProtoMessage() {}

func (x *ProximityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProximityResponse.ProtoReflect.Descriptor instead.
func (*ProximityResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{34}
}

func (x *ProximityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProximityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProximityResponse) GetNearKeyPoint() bool {
	if x != nil {
		return x.NearKeyPoint
	}
	return false
}

func (x *ProximityResponse) GetNearbyKeyPoint() *KeyPoint {
	if x != nil {
		return x.NearbyKeyPoint
	}
	return nil
}

func (x *ProximityResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type CompleteExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteExecutionRequest) Reset() {
	*x = CompleteExecutionRequest{}
	mi := &file_tour_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteExecutionRequest) ProtoMessage() {}

func (x *CompleteExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteExecutionRequest.ProtoReflect.Descriptor instead.
func (*CompleteExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{35}
}

func (x *CompleteExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CompleteExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type AbandonExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonExecutionRequest) Reset() {
	*x = AbandonExecutionRequest{}
	mi := &file_tour_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonExecutionRequest) ProtoMessage() {}

func (x *AbandonExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonExecutionRequest.ProtoReflect.Descriptor instead.
func (*AbandonExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{36}
}

func (x *AbandonExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *AbandonExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_tour_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{37}
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

var File_tour_proto protoreflect.FileDescriptor

const file_tour_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tour.proto\x12\x04tour\"\x97\x01\n" +
	"\x11CreateTourRequest\x12\x18\n" +
	"\aguideId\x18\x01 \x01(\tR\aguideId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"b\n" +
	"\fTourResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x04tour\x18\x03 \x01(\v2\n" +
	".tour.TourR\x04tour\"\xaa\x02\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aguideId\x18\x02 \x01(\tR\aguideId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12 \n" +
	"\visPublished\x18\t \x01(\bR\visPublished\x12 \n" +
	"\vpublishedAt\x18\n" +
	" \x01(\tR\vpublishedAt\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\"O\n" +
	"\x0fGetToursRequest\x12$\n" +
	"\rpublishedOnly\x18\x01 \x01(\bR\rpublishedOnly\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x11GetMyToursRequest\x12\x18\n" +
	"\aguideId\x18\x01 \x01(\tR\aguideId\"D\n" +
	"\x12GetTourByIdRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"e\n" +
	"\rToursResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x05tours\x18\x03 \x03(\v2\n" +
	".tour.TourR\x05tours\"\\\n" +
	"\x12PublishTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x18\n" +
	"\aguideId\x18\x02 \x01(\tR\aguideId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\xe2\x01\n" +
	"\x12AddKeyPointRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x18\n" +
	"\aguideId\x18\x02 \x01(\tR\aguideId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12\x14\n" +
	"\x05order\x18\b \x01(\x05R\x05order\"r\n" +
	"\x10KeyPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\bkeyPoint\x18\x03 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint\"\xce\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12\x14\n" +
	"\x05order\x18\b \x01(\x05R\x05order\"E\n" +
	"\x13GetKeyPointsRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"\x97\x01\n" +
	"\x11KeyPointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\tkeyPoints\x18\x03 \x03(\v2\x0e.tour.KeyPointR\tkeyPoints\x12 \n" +
	"\visPurchased\x18\x04 \x01(\bR\visPurchased\"\xef\x01\n" +
	"\x15UpdateKeyPointRequest\x12\x1e\n" +
	"\n" +
	"keyPointId\x18\x01 \x01(\tR\n" +
	"keyPointId\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12\x18\n" +
	"\aguideId\x18\x03 \x01(\tR\aguideId\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\"i\n" +
	"\x15DeleteKeyPointRequest\x12\x1e\n" +
	"\n" +
	"keyPointId\x18\x01 \x01(\tR\n" +
	"keyPointId\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12\x18\n" +
	"\aguideId\x18\x03 \x01(\tR\aguideId\"L\n" +
	"\x16DeleteKeyPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\x15UpdatePositionRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"2\n" +
	"\x12GetPositionRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\"r\n" +
	"\x10PositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.tour.PositionR\bposition\"\x80\x01\n" +
	"\bPosition\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\"H\n" +
	"\x10AddToCartRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\"M\n" +
	"\x15RemoveFromCartRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\".\n" +
	"\x0eGetCartRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\"j\n" +
	"\fCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04cart\x18\x03 \x01(\v2\x12.tour.ShoppingCartR\x04cart\"r\n" +
	"\fShoppingCart\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.tour.CartItemR\x05items\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x03 \x01(\x01R\n" +
	"totalPrice\"T\n" +
	"\bCartItem\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x1a\n" +
	"\btourName\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"/\n" +
	"\x0fCheckoutRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\"s\n" +
	"\x10CheckoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x06tokens\x18\x03 \x03(\v2\x13.tour.PurchaseTokenR\x06tokens\"_\n" +
	"\rPurchaseToken\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12 \n" +
	"\vpurchasedAt\x18\x03 \x01(\tR\vpurchasedAt\"\x9b\x01\n" +
	"\x15StartExecutionRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12$\n" +
	"\rstartLatitude\x18\x03 \x01(\x01R\rstartLatitude\x12&\n" +
	"\x0estartLongitude\x18\x04 \x01(\x01R\x0estartLongitude\"z\n" +
	"\x11ExecutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\texecution\x18\x03 \x01(\v2\x13.tour.TourExecutionR\texecution\"\xd0\x02\n" +
	"\rTourExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06tourId\x18\x03 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartedAt\x18\x05 \x01(\tR\tstartedAt\x12 \n" +
	"\vcompletedAt\x18\x06 \x01(\tR\vcompletedAt\x12\"\n" +
	"\flastActivity\x18\a \x01(\tR\flastActivity\x124\n" +
	"\rstartPosition\x18\b \x01(\v2\x0e.tour.PositionR\rstartPosition\x12G\n" +
	"\x12completedKeypoints\x18\t \x03(\v2\x17.tour.CompletedKeyPointR\x12completedKeypoints\"U\n" +
	"\x11CompletedKeyPoint\x12\x1e\n" +
	"\n" +
	"keypointId\x18\x01 \x01(\tR\n" +
	"keypointId\x12 \n" +
	"\vcompletedAt\x18\x02 \x01(\tR\vcompletedAt\"\xad\x01\n" +
	"\x15CheckProximityRequest\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\tR\ttouristId\x12(\n" +
	"\x0fcurrentLatitude\x18\x03 \x01(\x01R\x0fcurrentLatitude\x12*\n" +
	"\x10currentLongitude\x18\x04 \x01(\x01R\x10currentLongitude\"\xbf\x01\n" +
	"\x11ProximityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\fnearKeyPoint\x18\x03 \x01(\bR\fnearKeyPoint\x126\n" +
	"\x0enearbyKeyPoint\x18\x04 \x01(\v2\x0e.tour.KeyPointR\x0enearbyKeyPoint\x12\x1a\n" +
	"\bdistance\x18\x05 \x01(\x01R\bdistance\"Z\n" +
	"\x18CompleteExecutionRequest\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\tR\ttouristId\"Y\n" +
	"\x17AbandonExecutionRequest\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\tR\ttouristId\"U\n" +
	"\x13GetExecutionRequest\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\tR\ttouristId2\xb2\n" +
	"\n" +
	"\vTourService\x129\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x12.tour.TourResponse\x126\n" +
	"\bGetTours\x12\x15.tour.GetToursRequest\x1a\x13.tour.ToursResponse\x12;\n" +
	"\vGetTourById\x12\x18.tour.GetTourByIdRequest\x1a\x12.tour.TourResponse\x12;\n" +
	"\vPublishTour\x12\x18.tour.PublishTourRequest\x1a\x12.tour.TourResponse\x12:\n" +
	"\n" +
	"GetMyTours\x12\x17.tour.GetMyToursRequest\x1a\x13.tour.ToursResponse\x12?\n" +
	"\vAddKeyPoint\x12\x18.tour.AddKeyPointRequest\x1a\x16.tour.KeyPointResponse\x12B\n" +
	"\fGetKeyPoints\x12\x19.tour.GetKeyPointsRequest\x1a\x17.tour.KeyPointsResponse\x12E\n" +
	"\x0eUpdateKeyPoint\x12\x1b.tour.UpdateKeyPointRequest\x1a\x16.tour.KeyPointResponse\x12K\n" +
	"\x0eDeleteKeyPoint\x12\x1b.tour.DeleteKeyPointRequest\x1a\x1c.tour.DeleteKeyPointResponse\x12E\n" +
	"\x0eUpdatePosition\x12\x1b.tour.UpdatePositionRequest\x1a\x16.tour.PositionResponse\x12F\n" +
	"\x12GetCurrentPosition\x12\x18.tour.GetPositionRequest\x1a\x16.tour.PositionResponse\x127\n" +
	"\tAddToCart\x12\x16.tour.AddToCartRequest\x1a\x12.tour.CartResponse\x12A\n" +
	"\x0eRemoveFromCart\x12\x1b.tour.RemoveFromCartRequest\x1a\x12.tour.CartResponse\x123\n" +
	"\aGetCart\x12\x14.tour.GetCartRequest\x1a\x12.tour.CartResponse\x129\n" +
	"\bCheckout\x12\x15.tour.CheckoutRequest\x1a\x16.tour.CheckoutResponse\x12J\n" +
	"\x12StartTourExecution\x12\x1b.tour.StartExecutionRequest\x1a\x17.tour.ExecutionResponse\x12F\n" +
	"\x0eCheckProximity\x12\x1b.tour.CheckProximityRequest\x1a\x17.tour.ProximityResponse\x12G\n" +
	"\fCompleteTour\x12\x1e.tour.CompleteExecutionRequest\x1a\x17.tour.ExecutionResponse\x12E\n" +
	"\vAbandonTour\x12\x1d.tour.AbandonExecutionRequest\x1a\x17.tour.ExecutionResponse\x12B\n" +
	"\fGetExecution\x12\x19.tour.GetExecutionRequest\x1a\x17.tour.ExecutionResponseB*Z(tourism-microservices/tour-service/protob\x06proto3"

var (
	file_tour_proto_rawDescOnce sync.Once
	file_tour_proto_rawDescData []byte
)

func file_tour_proto_rawDescGZIP() []byte {
	file_tour_proto_rawDescOnce.Do(func() {
		file_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)))
	})
	return file_tour_proto_rawDescData
}

var file_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_tour_proto_goTypes = []any{
	(*CreateTourRequest)(nil),        // 0: tour.CreateTourRequest
	(*TourResponse)(nil),             // 1: tour.TourResponse
	(*Tour)(nil),                     // 2: tour.Tour
	(*GetToursRequest)(nil),          // 3: tour.GetToursRequest
	(*GetMyToursRequest)(nil),        // 4: tour.GetMyToursRequest
	(*GetTourByIdRequest)(nil),       // 5: tour.GetTourByIdRequest
	(*ToursResponse)(nil),            // 6: tour.ToursResponse
	(*PublishTourRequest)(nil),       // 7: tour.PublishTourRequest
	(*AddKeyPointRequest)(nil),       // 8: tour.AddKeyPointRequest
	(*KeyPointResponse)(nil),         // 9: tour.KeyPointResponse
	(*KeyPoint)(nil),                 // 10: tour.KeyPoint
	(*GetKeyPointsRequest)(nil),      // 11: tour.GetKeyPointsRequest
	(*KeyPointsResponse)(nil),        // 12: tour.KeyPointsResponse
	(*UpdateKeyPointRequest)(nil),    // 13: tour.UpdateKeyPointRequest
	(*DeleteKeyPointRequest)(nil),    // 14: tour.DeleteKeyPointRequest
	(*DeleteKeyPointResponse)(nil),   // 15: tour.DeleteKeyPointResponse
	(*UpdatePositionRequest)(nil),    // 16: tour.UpdatePositionRequest
	(*GetPositionRequest)(nil),       // 17: tour.GetPositionRequest
	(*PositionResponse)(nil),         // 18: tour.PositionResponse
	(*Position)(nil),                 // 19: tour.Position
	(*AddToCartRequest)(nil),         // 20: tour.AddToCartRequest
	(*RemoveFromCartRequest)(nil),    // 21: tour.RemoveFromCartRequest
	(*GetCartRequest)(nil),           // 22: tour.GetCartRequest
	(*CartResponse)(nil),             // 23: tour.CartResponse
	(*ShoppingCart)(nil),             // 24: tour.ShoppingCart
	(*CartItem)(nil),                 // 25: tour.CartItem
	(*CheckoutRequest)(nil),          // 26: tour.CheckoutRequest
	(*CheckoutResponse)(nil),         // 27: tour.CheckoutResponse
	(*PurchaseToken)(nil),            // 28: tour.PurchaseToken
	(*StartExecutionRequest)(nil),    // 29: tour.StartExecutionRequest
	(*ExecutionResponse)(nil),        // 30: tour.ExecutionResponse
	(*TourExecution)(nil),            // 31: tour.TourExecution
	(*CompletedKeyPoint)(nil),        // 32: tour.CompletedKeyPoint
	(*CheckProximityRequest)(nil),    // 33: tour.CheckProximityRequest
	(*ProximityResponse)(nil),        // 34: tour.ProximityResponse
	(*CompleteExecutionRequest)(nil), // 35: tour.CompleteExecutionRequest
	(*AbandonExecutionRequest)(nil),  // 36: tour.AbandonExecutionRequest
	(*GetExecutionRequest)(nil),      // 37: tour.GetExecutionRequest
}
var file_tour_proto_depIdxs = []int32{
	2,  // 0: tour.TourResponse.tour:type_name -> tour.Tour
	2,  // 1: tour.ToursResponse.tours:type_name -> tour.Tour
	10, // 2: tour.KeyPointResponse.keyPoint:type_name -> tour.KeyPoint
	10, // 3: tour.KeyPointsResponse.keyPoints:type_name -> tour.KeyPoint
	19, // 4: tour.PositionResponse.position:type_name -> tour.Position
	24, // 5: tour.CartResponse.cart:type_name -> tour.ShoppingCart
	25, // 6: tour.ShoppingCart.items:type_name -> tour.CartItem
	28, // 7: tour.CheckoutResponse.tokens:type_name -> tour.PurchaseToken
	31, // 8: tour.ExecutionResponse.execution:type_name -> tour.TourExecution
	19, // 9: tour.TourExecution.startPosition:type_name -> tour.Position
	32, // 10: tour.TourExecution.completedKeypoints:type_name -> tour.CompletedKeyPoint
	10, // 11: tour.ProximityResponse.nearbyKeyPoint:type_name -> tour.KeyPoint
	0,  // 12: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	3,  // 13: tour.TourService.GetTours:input_type -> tour.GetToursRequest
	5,  // 14: tour.TourService.GetTourById:input_type -> tour.GetTourByIdRequest
	7,  // 15: tour.TourService.PublishTour:input_type -> tour.PublishTourRequest
	4,  // 16: tour.TourService.GetMyTours:input_type -> tour.GetMyToursRequest
	8,  // 17: tour.TourService.AddKeyPoint:input_type -> tour.AddKeyPointRequest
	11, // 18: tour.TourService.GetKeyPoints:input_type -> tour.GetKeyPointsRequest
	13, // 19: tour.TourService.UpdateKeyPoint:input_type -> tour.UpdateKeyPointRequest
	14, // 20: tour.TourService.DeleteKeyPoint:input_type -> tour.DeleteKeyPointRequest
	16, // 21: tour.TourService.UpdatePosition:input_type -> tour.UpdatePositionRequest
	17, // 22: tour.TourService.GetCurrentPosition:input_type -> tour.GetPositionRequest
	20, // 23: tour.TourService.AddToCart:input_type -> tour.AddToCartRequest
	21, // 24: tour.TourService.RemoveFromCart:input_type -> tour.RemoveFromCartRequest
	22, // 25: tour.TourService.GetCart:input_type -> tour.GetCartRequest
	26, // 26: tour.TourService.Checkout:input_type -> tour.CheckoutRequest
	29, // 27: tour.TourService.StartTourExecution:input_type -> tour.StartExecutionRequest
	33, // 28: tour.TourService.CheckProximity:input_type -> tour.CheckProximityRequest
	35, // 29: tour.TourService.CompleteTour:input_type -> tour.CompleteExecutionRequest
	36, // 30: tour.TourService.AbandonTour:input_type -> tour.AbandonExecutionRequest
	37, // 31: tour.TourService.GetExecution:input_type -> tour.GetExecutionRequest
	1,  // 32: tour.TourService.CreateTour:output_type -> tour.TourResponse
	6,  // 33: tour.TourService.GetTours:output_type -> tour.ToursResponse
	1,  // 34: tour.TourService.GetTourById:output_type -> tour.TourResponse
	1,  // 35: tour.TourService.PublishTour:output_type -> tour.TourResponse
	6,  // 36: tour.TourService.GetMyTours:output_type -> tour.ToursResponse
	9,  // 37: tour.TourService.AddKeyPoint:output_type -> tour.KeyPointResponse
	12, // 38: tour.TourService.GetKeyPoints:output_type -> tour.KeyPointsResponse
	9,  // 39: tour.TourService.UpdateKeyPoint:output_type -> tour.KeyPointResponse
	15, // 40: tour.TourService.DeleteKeyPoint:output_type -> tour.DeleteKeyPointResponse
	18, // 41: tour.TourService.UpdatePosition:output_type -> tour.PositionResponse
	18, // 42: tour.TourService.GetCurrentPosition:output_type -> tour.PositionResponse
	23, // 43: tour.TourService.AddToCart:output_type -> tour.CartResponse
	23, // 44: tour.TourService.RemoveFromCart:output_type -> tour.CartResponse
	23, // 45: tour.TourService.GetCart:output_type -> tour.CartResponse
	27, // 46: tour.TourService.Checkout:output_type -> tour.CheckoutResponse
	30, // 47: tour.TourService.StartTourExecution:output_type -> tour.ExecutionResponse
	34, // 48: tour.TourService.CheckProximity:output_type -> tour.ProximityResponse
	30, // 49: tour.TourService.CompleteTour:output_type -> tour.ExecutionResponse
	30, // 50: tour.TourService.AbandonTour:output_type -> tour.ExecutionResponse
	30, // 51: tour.TourService.GetExecution:output_type -> tour.ExecutionResponse
	32, // [32:52] is the sub-list for method output_type
	12, // [12:32] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tour_proto_init() }
func file_tour_proto_init() {
	if File_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_proto_goTypes,
		DependencyIndexes: file_tour_proto_depIdxs,
		MessageInfos:      file_tour_proto_msgTypes,
	}.Build()
	File_tour_proto = out.File
	file_tour_proto_goTypes = nil
	file_tour_proto_depIdxs = nil
}
